spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
generator:
  target-schema: public
  java-package: com.example.model
  data-class-type: plain
  build-path: generated-data-classes
postgresql:
  conversion-map:
    character varying: java.lang.String
    character: java.lang.String
    text: java.lang.String
    smallint: short
    integer: int
    bigint: long
    real: float
    double precision: double
    numeric: java.math.BigDecimal
    boolean: boolean
    bytea: byte[]
    date: java.sql.Date
    timestamp without time zone: java.sql.Timestamp
mysql:
  conversion-map:
    varchar: java.lang.String
    char: java.lang.String
    tinytext: java.lang.String
    text: java.lang.String
    mediumtext: java.lang.String
    longtext: java.lang.String
    tinyblob: byte[]
    blob: byte[]
    mediumblob: byte[]
    longblob: byte[]
    smallint: short
    int: int
    bigint: long
    double: double
    decimal: java.math.BigDecimal
    date: java.sql.Date
    datetime: java.sql.Timestamp
    timestamp: java.sql.Timestamp
    time: java.sql.Time
